services:
  - type: web
    name: rustpbx
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: starter
    envVars:
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 8080
    ports:
      - port: 8080
        protocol: tcp
    healthCheckPath: /
    autoDeploy: true
